---
name: Release Pipeline

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java-version: [ '17' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create Image
        run: ./gradlew jpackageImage

      - name: Zip jpackage output
        if: runner.os == 'Windows'
        run: powershell Compress-Archive -Path build/jpackage/app/* -DestinationPath voiceart-${{runner.os}}.zip

      - name: Zip jpackage output
        if: runner.os == 'Linux'
        run: zip -r voiceart-${{runner.os}}.zip build/jpackage/app/


      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: voiceart-${{runner.os}}
          path: voiceart-${{runner.os}}.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: voiceart-Windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: voiceart-Linux

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: |
            voiceart-Windows.zip
            voiceart-Linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}