---
name: Release Pipeline

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create Image
        run: ./gradlew jpackageImage

      - name: Zip jpackage output
        run: powershell Compress-Archive -Path build/jpackage/app/* -DestinationPath voiceart-windows.zip

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: voiceart-windows
          path: voiceart-windows.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: voiceart-windows

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: voiceart-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}